names:
  0: apple,
  1: backpack,
  2: banana,
  3: bottle,
  4: bowl,
  5: cell phone,
  6: chair,
  7: cup,
  8: fork,
  9: keyboard,
  10: knife,
  11: laptop,
  12: mouse,
  13: orange,
  14: remote,
  15: spoon,
  16: suitcase,
  17: teddy bear,
  18: tie,
  19: umbrella,
  20: wine glass,
  21: human hand,
  22: door handle,
  23: boot,
  24: glove,
  25: clothing,
  26: sock,
  27: book,
  28: scissors,
  29: wallet,
  30: keys,
  31: brush,
  32: toothbrush,
  33: hairdryer,
  34: plate,
  35: spatula,
  36: towel,
  37: sponge,
  38: pillow,
  39: blanket,
  40: lamp,
  41: pen,
  42: notebook,
  43: marker,
  44: stapler,
  45: tape,
  46: calculator,
  47: headphones,
  48: microphone,
  49: camera,
  50: glasses,
  51: hat,
  52: scarf,
  53: watch,
  54: bracelet,
  55: ring,
  56: belt,
  57: shoe,
  58: sandal
path: C:/Users/Thoma/ProjetYOLO/GLO-7030/YOLO4BrainIAV1/Combined_dataset
train: train
test: test
val: validation
